name:                vimwiki-publishing-system
version:             0.1.0.0
github:              "ajkavanagh/vimwiki-publishing-system"
license:             BSD3
author:              "Alex Kavanagh"
maintainer:          "alex@ajkavanagh.co.uk"
copyright:           "(c) AJKavanagh"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ajkavanagh/vimwiki-publishing-system#readme>

dependencies:
- base >= 4.7 && < 5
- ghc-tcplugins-extra >= 0.3 && < 0.4

library:
  source-dirs:
    - src
    - templates
  dependencies:
    - aeson
    - bytestring
    - co-log
    - co-log-core
    - co-log-polysemy
    - conduit
    - cryptonite
    - data-default
    - data-default-class
    - directory
    - dlist
    - filepath
    - file-embed
    - generic-deriving
    - ginger
    - hashable
    - network-uri
    - microlens
    - microlens-th
    - microlens-platform
    - optparse-applicative
    - pandoc
    - pandoc-types
    - parsec
    - parser-combinators
    - polysemy
    - polysemy-plugin
    - safe
    - scientific
    - split
    - system-locale
    - temporary
    - text
    - text-show
    - time
    - titlecase
    - unix
    - unordered-containers
    - utf8-string
    - yaml
  default-extensions:
    - DataKinds
    - FlexibleContexts
    - GADTs
    - LambdaCase
    - PolyKinds
    - RankNTypes
    - ScopedTypeVariables
    - TypeApplications
    - TypeOperators
    - TypeFamilies

executables:
  sitegen:
    main:                VPS.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is VPS
    - -O2
    - -flate-specialise
    - -fspecialise-aggressively
    - -fprint-potential-instances
    - -fplugin=Polysemy.Plugin
    dependencies:
    - vimwiki-publishing-system
    - polysemy
    - polysemy-plugin
    default-extensions:
    - DataKinds
    - FlexibleContexts
    - GADTs
    - LambdaCase
    - PolyKinds
    - RankNTypes
    - ScopedTypeVariables
    - TypeApplications
    - TypeOperators
    - TypeFamilies

tests:
  vimwiki-publishing-system-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=Polysemy.Plugin
    dependencies:
    - bytestring
    - co-log-core
    - co-log-polysemy
    - data-default
    - data-default-class
    - hspec
    - pandoc
    - pandoc-types
    - polysemy
    - polysemy-plugin
    - raw-strings-qq
    - text
    - unordered-containers
    - vimwiki-publishing-system
