# lts-16.3 is haskell 8.8.3
resolver: lts-16.3

packages:
- .

extra-deps:
  # polysemy 1.3.0.0
  - git: https://github.com/polysemy-research/polysemy.git
    commit: 3c731186cb5ebcfc9319586e0b691b985c6730e2
  # polysemy-plugin  - 0.2.5.0
  - git: https://github.com/polysemy-research/polysemy.git
    commit: 3c731186cb5ebcfc9319586e0b691b985c6730e2
    subdirs:
      - polysemy-plugin
  # co-log-polysemy (latest commit is 0.401)
  #- git: https://github.com/kowainik/co-log.git
    #commit: 13f6c31d4eb9290c5a5c1ea8de0b2f9f8d0957fa
    #commit: 947f9fb0a0b8bfdfad21255157cec53b48382c89
    #commit: 9227c7f2b06813c8a1354b1057255fab3c885c6b
    #subdirs:
      #- co-log
      #- co-log-core
      #- co-log-polysemy
  # system-locale
  - git: https://github.com/ajkavanagh/system-locale.git
    commit: 7571b0ebf125338d47ed45fbc6c18b2ee3a22e81
  - first-class-families-0.6.0.0
  - ghc-tcplugins-extra-0.3.2@sha256:1bbfd4449c3669a31618ea0ebc5d00d980a53988daad3b6218bab5c8cdff268d,1687
  - time-1.9.3
